// Builds dist/vendor/lucide-icons.js: only the Lucide icons this app references, plus a tiny
// createIcons() with the same output as Lucide's (svg attributes, classes, aria-hidden).
// Usage: node tools/build-icons.mjs        (write)
//        node tools/build-icons.mjs --check (exit 1 if the subset is stale or a name is unknown)
import {readFileSync, writeFileSync, readdirSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import vm from 'node:vm';

const root = fileURLToPath(new URL('..', import.meta.url));
const OUT = `${root}dist/vendor/lucide-icons.js`;

export function loadLucide() {
  const ctx = {};
  ctx.globalThis = ctx;
  vm.createContext(ctx);
  vm.runInContext(readFileSync(`${root}tools/lucide-full.min.js`, 'utf8'), ctx);
  return ctx.lucide;
}

const pascal = name => name.replace(/(^|-)([a-z0-9])/g, (_, __, c) => c.toUpperCase());

// Every quoted kebab-case string in the app sources that names a Lucide icon. Over-matching is
// harmless (a few extra icons); this way icons chosen in data or ternaries are never missed.
export function usedIcons(lucide = loadLucide()) {
  const files = readdirSync(`${root}dist`).filter(f => /\.(js|html)$/.test(f));
  const names = new Set();
  for (const f of files) {
    const src = readFileSync(`${root}dist/${f}`, 'utf8');
    for (const [, name] of src.matchAll(/["'`]([a-z][a-z0-9]*(?:-[a-z0-9]+)*)["'`]/g))
      if (lucide.icons[pascal(name)]) names.add(name);
  }
  return [...names].sort();
}

// Literal references that must exist (data-lucide="x", icon('x'), icon:'x').
export function referencedIcons() {
  const files = readdirSync(`${root}dist`).filter(f => /\.(js|html)$/.test(f));
  const names = new Set();
  for (const f of files) {
    const src = readFileSync(`${root}dist/${f}`, 'utf8');
    for (const re of [
      /data-lucide="([a-z0-9-]+)"/g,
      /\bicon\(\s*'([a-z0-9-]+)'\s*\)/g,
      /\bicon:\s*'([a-z0-9-]+)'/g
    ])
      for (const [, name] of src.matchAll(re)) names.add(name);
  }
  return [...names].sort();
}

export function buildSource(lucide = loadLucide()) {
  const names = usedIcons(lucide);
  const icons = Object.fromEntries(names.map(n => [n, lucide.icons[pascal(n)]]));
  return `// Generated by tools/build-icons.mjs from Lucide (ISC, see LUCIDE-LICENSE.txt). Do not edit by hand.
// ${names.length} icons. Same markup as lucide.createIcons(): <i data-lucide="name"> → <svg class="lucide lucide-name">.
(() => {
  const ICONS = ${JSON.stringify(icons)};
  const BASE = {xmlns: 'http://www.w3.org/2000/svg', width: 24, height: 24, viewBox: '0 0 24 24', fill: 'none', stroke: 'currentColor', 'stroke-width': 2, 'stroke-linecap': 'round', 'stroke-linejoin': 'round'};
  const NS = 'http://www.w3.org/2000/svg';
  const make = ([tag, attrs, children]) => {
    const el = document.createElementNS(NS, tag);
    for (const k of Object.keys(attrs)) el.setAttribute(k, String(attrs[k]));
    if (children) for (const c of children) el.appendChild(make(c));
    return el;
  };
  function replace(el) {
    const name = el.getAttribute('data-lucide'), nodes = ICONS[name];
    if (!nodes) return console.warn(\`[icons] "\${name}" is not in the icon subset; run node tools/build-icons.mjs\`);
    const own = Object.fromEntries([...el.attributes].map(a => [a.name, a.value]));
    const labelled = Object.keys(own).some(k => k.startsWith('aria-') || k === 'role' || k === 'title');
    const attrs = {...BASE, 'data-lucide': name, ...(labelled ? {} : {'aria-hidden': 'true'}), ...own};
    attrs.class = ['lucide', \`lucide-\${name}\`, ...(own.class || '').split(' ')].filter((c, i, a) => c && a.indexOf(c) === i).join(' ');
    const svg = make(['svg', attrs, nodes]);
    el.parentNode?.replaceChild(svg, el);
  }
  window.lucide = {createIcons: ({root = document} = {}) => root.querySelectorAll('[data-lucide]').forEach(el => el.tagName.toLowerCase() !== 'svg' && replace(el))};
})();
`;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const lucide = loadLucide();
  const missing = referencedIcons().filter(n => !lucide.icons[pascal(n)]);
  if (missing.length) {
    console.error('Unknown Lucide icon names:', missing.join(', '));
    process.exit(1);
  }
  const src = buildSource(lucide);
  if (process.argv.includes('--check')) {
    let current = '';
    try {
      current = readFileSync(OUT, 'utf8');
    } catch {}
    if (current !== src) {
      console.error('dist/vendor/lucide-icons.js is out of date; run node tools/build-icons.mjs');
      process.exit(1);
    }
    console.log('icon subset up to date');
  } else {
    writeFileSync(OUT, src);
    console.log(
      `wrote ${usedIcons(lucide).length} icons to dist/vendor/lucide-icons.js (${src.length} bytes)`
    );
  }
}
